name: Inner Sanctum Sports
favicon: null
layout_spectrum: 0.58114
typography_spectrum: 0.57482
title: Infinite Greatness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c41d03'
    - '#17a0bc'
    - '#265757'
  brandStrength: 0.6875
  lightness: 0.9837440373376012
  saturation: 0.8990411644335836
  rhythmicContrast: 0.75
purpose: []
