name: Inner Sanctum Sports
favicon: null
layout_spectrum: 0.48704564524814487
typography_spectrum: 0.57482
title: Infinite Greatness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#182433'
    - '#517dc0'
    - '#e4f2ff'
    - '#a6c1ed'
  brandStrength: 0.6276131076738238
  lightness: 0.9837440373376012
  saturation: 0.8990411644335836
  rhythmicContrast: 0.828289607539773
purpose: []
